apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
  namespace: devops
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==      # base64 for "root"
  SPRING_DATASOURCE_PASSWORD: ""            # empty string, can be empty base64 ""
