apiVersion: v1
kind: Secret
metadata:
  name: spring-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: c3ByaW5n # "spring" in base64
  SPRING_DATASOURCE_PASSWORD: c3ByaW5nMTIz # "spring123" in base64

